version: '3.7'
services:
  web:
    container_name: web
    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbit
      - es
  db:
    container_name: db
    hostname: db
    image: postgres:12.0-alpine
    restart: on-failure
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.8.19-management
    restart: on-failure
    env_file:
      - ./.env.dev
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    container_name: celery
    hostname: celery
    build: .
    command: celery -A server worker -l INFO
    restart: on-failure
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - rabbit
  celery-beat:
    container_name: celery-beat
    hostname: celery-beat
    build: .
    command: celery -A server beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: on-failure
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - rabbit
  es:
    container_name: es
    hostname: es
    image: elasticsearch:7.8.1
    restart: on-failure
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    restart: on-failure
    hostname: mongo
    env_file:
      - ./.env.dev
    ports:
      - "27017:27017"

volumes:
  postgres_data:
